export const BILLING_ACCOUNT_CREATED = 'BILLING_ACCOUNT_CREATED';
export const BILLING_ACCOUNT_CREATING = 'BILLING_ACCOUNT_CREATING';
export const BILLING_ACCOUNT_CREATION_ERROR = 'BILLING_ACCOUNT_CREATION_ERROR';
export const BILLING_ACCOUNT_UPDATED = 'BILLING_ACCOUNT_UPDATED';
export const BILLING_ACCOUNT_UPDATING = 'BILLING_ACCOUNT_UPDATING';
export const BILLING_ACCOUNT_UPDATING_ERROR = 'BILLING_ACCOUNT_UPDATING_ERROR';