export const CATEGORY_CREATED = 'CATEGORY_CREATED';
export const CATEGORY_CREATING = 'CATEGORY_CREATING';
export const CATEGORY_CREATION_ERROR = 'CATEGORY_CREATION_ERROR';
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED';
export const CATEGORY_UPDATING = 'CATEGORY_UPDATING';
export const CATEGORY_UPDATING_ERROR = 'CATEGORY_UPDATING_ERROR';