export const EXPENSE_CREATED = 'EXPENSE_CREATED';
export const EXPENSE_CREATING = 'EXPENSE_CREATING';
export const EXPENSE_CREATION_ERROR = 'EXPENSE_CREATION_ERROR';
export const EXPENSE_UPDATED = 'EXPENSE_UPDATED';
export const EXPENSE_UPDATING = 'EXPENSE_UPDATING';
export const EXPENSE_UPDATING_ERROR = 'EXPENSE_UPDATING_ERROR';