export const LOYALTY_CARD_CREATED = 'LOYALTY_CARD_CREATED';
export const LOYALTY_CARD_CREATING = 'LOYALTY_CARD_CREATING';
export const LOYALTY_CARD_CREATION_ERROR = 'LOYALTY_CARD_CREATION_ERROR';
export const LOYALTY_CARD_UPDATED = 'LOYALTY_CARD_UPDATED';
export const LOYALTY_CARD_UPDATING = 'LOYALTY_CARD_UPDATING';
export const LOYALTY_CARD_UPDATING_ERROR = 'LOYALTY_CARD_UPDATING_ERROR';