export const SUB_CATEGORY_CREATED = 'SUB_CATEGORY_CREATED';
export const SUB_CATEGORY_CREATING = 'SUB_CATEGORY_CREATING';
export const SUB_CATEGORY_CREATION_ERROR = 'SUB_CATEGORY_CREATION_ERROR';
export const SUB_CATEGORY_UPDATED = 'SUB_CATEGORY_UPDATED';
export const SUB_CATEGORY_UPDATING = 'SUB_CATEGORY_UPDATING';
export const SUB_CATEGORY_UPDATING_ERROR = 'SUB_CATEGORY_UPDATING_ERROR';